# Generated by Django 4.2.11 on 2024-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="short_description",
        ),
        migrations.AddField(
            model_name="movie",
            name="content_rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(default="/assets/404.png"),
        ),
    ]
