# Generated by Django 4.2.11 on 2024-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="thumbnail",
            field=models.TextField(
                default="/static/banner404.png", max_length=10000, null=True
            ),
        ),
    ]
