# Generated by Django 4.2.11 on 2024-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='content_rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(),
        ),
    ]
