# Generated by Django 4.2.11 on 2024-04-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="media",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="media",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
