# Generated by Django 4.2.11 on 2024-04-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_profile_ratings"),
        ("web", "0002_alter_book_options_alter_media_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="user.profile",
            ),
        ),
    ]
