# Generated by Django 4.2.11 on 2024-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_genre_name_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.URLField(default='/static/banner404.png', max_length=10000, null=True),
        ),
    ]
