# Generated by Django 4.2.11 on 2024-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_remove_movie_short_description_movie_content_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(default="/static/banner404.png"),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
