# Generated by Django 4.2.11 on 2024-05-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_rating_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="service_rating",
            field=models.FloatField(null=True),
        ),
    ]
