# Generated by Django 4.2.11 on 2024-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rating_completed_alter_rating_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="translated_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
