# Generated by Django 4.2.11 on 2024-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_movie_poster_url_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.AlterField(
            model_name="movie",
            name="content_rating",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(blank=True, to="web.director"),
        ),
    ]
