# Generated by Django 4.2.11 on 2024-05-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_book_service_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(null=True),
        ),
    ]
