# Generated by Django 4.2.11 on 2024-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_director_remove_movie_director_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="content_rating",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="web.genre"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(default="/static/banner404.png", null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(null=True),
        ),
    ]
