# Generated by Django 4.2.11 on 2024-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_movie_content_rating_alter_movie_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
