# Generated by Django 4.2.11 on 2024-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_genre_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="user_ratings",
        ),
        migrations.AddField(
            model_name="rating",
            name="favorited",
            field=models.BooleanField(default=False),
        ),
    ]
