# Generated by Django 4.2.11 on 2024-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_remove_movie_user_ratings_rating_favorited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="object_id",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="stars",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Terrible"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=0,
            ),
        ),
    ]
