# Generated by Django 4.2.11 on 2024-04-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_rating_object_id_alter_rating_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="object_id",
        ),
        migrations.AddField(
            model_name="rating",
            name="media",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="web.movie",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
