# Generated by Django 4.2.11 on 2024-04-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_ratings"),
        ("web", "0009_remove_rating_content_type_remove_rating_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="user.profile",
            ),
        ),
    ]
