# Generated by Django 4.2.11 on 2024-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_book_pages"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_genres",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_by_users", to="web.genre"
            ),
        ),
    ]
