# Generated by Django 4.2.11 on 2024-04-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_rating_content_type_remove_rating_object_id_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ratings",
            field=models.ManyToManyField(related_name="ratings", to="web.rating"),
        ),
    ]
