# Generated by Django 4.2.11 on 2024-04-17 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="ratings",
        ),
    ]
